services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'workout_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'passwd'
      MYSQL_ROOT_PASSWORD: 'passwd'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: